apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "syros-platform.fullname" . }}
  labels:
    {{- include "syros-platform.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "syros-platform.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "syros-platform.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "syros-platform.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.config.server.port }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.config.server.grpcPort }}
              protocol: TCP
            - name: websocket
              containerPort: {{ .Values.config.server.websocketPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: CONFIG_FILE
              value: "/etc/syros/config.toml"
            - name: RUST_LOG
              value: {{ .Values.config.logging.level | quote }}
            - name: SYROS_HOST
              value: {{ .Values.config.server.host | quote }}
            - name: SYROS_PORT
              value: {{ .Values.config.server.port | quote }}
            - name: SYROS_GRPC_PORT
              value: {{ .Values.config.server.grpcPort | quote }}
            - name: SYROS_WEBSOCKET_PORT
              value: {{ .Values.config.server.websocketPort | quote }}
            - name: SYROS_REDIS_URL
              value: {{ .Values.config.storage.redis.url | quote }}
            - name: SYROS_DATABASE_URL
              value: {{ .Values.config.database.url | quote }}
            - name: SYROS_CONSUL_URL
              value: {{ .Values.config.serviceDiscovery.consulUrl | quote }}
            - name: SYROS_SERVICE_NAME
              value: {{ .Values.config.serviceDiscovery.serviceName | quote }}
            - name: SYROS_SERVICE_ID
              value: {{ .Values.config.serviceDiscovery.serviceId | quote }}
          volumeMounts:
            - name: config
              mountPath: /etc/syros
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "syros-platform.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
