apiVersion: v1
kind: Service
metadata:
  name: {{ include "syros-platform.fullname" . }}
  labels:
    {{- include "syros-platform.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
      name: grpc
    - port: {{ .Values.service.websocketPort }}
      targetPort: websocket
      protocol: TCP
      name: websocket
  selector:
    {{- include "syros-platform.selectorLabels" . | nindent 4 }}
